# Generated by Django 2.2.7 on 2019-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
