# Generated by Django 2.2.6 on 2019-10-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinpoint',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restapi.User'),
            preserve_default=False,
        ),
    ]
