# Generated by Django 2.2.7 on 2019-11-27 10:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20191127_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
