# Generated by Django 2.2.6 on 2019-10-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_pinpoint_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pinpoint_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restapi.Pinpoint'),
            preserve_default=False,
        ),
    ]
