# Generated by Django 2.2.7 on 2019-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20191204_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.TextField(null=True),
        ),
    ]
