# Generated by Django 2.2.6 on 2019-11-06 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20191106_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinpoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='pinpoint',
            name='y',
        ),
        migrations.AddField(
            model_name='pinpoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
